# Generated by Django 5.1.7 on 2025-10-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('design', 'Graphic Design'), ('ai', 'AI work')], max_length=20),
        ),
    ]
