# Generated by Django 5.1.7 on 2025-12-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
