# Generated by Django 5.1.7 on 2026-05-23 06:33

import django.utils.timezone
from django.db import migrations, models


def create_default_admin_content(apps, schema_editor):
    SiteProfile = apps.get_model('main', 'SiteProfile')
    SEOSettings = apps.get_model('main', 'SEOSettings')
    SiteProfile.objects.get_or_create(name='Wambugu Moses')
    SEOSettings.objects.get_or_create(
        title='Wambugu Moses | AI Engineer, AI Agents & Agentic Systems'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown on the blog page.')),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Wambugu Moses | AI Engineer, AI Agents & Agentic Systems', max_length=180)),
                ('description', models.TextField(default='Wambugu Moses, also known as WambuguAI, builds AI agents, agentic systems, software products, and digital experiences.')),
                ('keywords', models.TextField(default='Wambugu Moses, Moses, WambuguAI, AI, artificial intelligence, AI agents, agentic systems, software engineer Kenya')),
                ('canonical_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Wambugu Moses', max_length=120)),
                ('headline', models.CharField(default='Software Engineer | Graphic Designer | Upcoming AI Engineer', max_length=220)),
                ('intro', models.TextField(default='Building tech solutions that inspire change. Advocate for sustainability & STEM mentoring.')),
                ('about_title', models.CharField(default='Who I am.', max_length=120)),
                ('about_text', models.TextField(default="I'm a versatile Software Developer, Graphic Designer, and aspiring AI Engineer. My journey blends creativity with technology, allowing me to design and build digital solutions that are functional and visually impactful.")),
                ('github_url', models.URLField(blank=True, default='https://github.com/Polymathh')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/in/wambugumoses/')),
                ('tiktok_url', models.URLField(blank=True, default='https://www.tiktok.com/@wambugu_ai')),
                ('whatsapp_url', models.URLField(blank=True, default='https://wa.me/+254704141329')),
                ('phone', models.CharField(blank=True, default='+254704141329', max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
        migrations.RunPython(create_default_admin_content, migrations.RunPython.noop),
    ]
