# Generated by Django 5.1.7 on 2026-05-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blogpost_seosettings_siteprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
    ]
