# Generated by Django 5.1.7 on 2026-05-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_siteprofile_facebook_url_siteprofile_instagram_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['display_order', '-published_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='display_order',
            field=models.PositiveIntegerField(default=100, help_text='Lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(default=100, help_text='Lower numbers appear first.'),
        ),
    ]
