# Generated by Django 5.1.7 on 2026-05-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_coursepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepayment',
            name='mpesa_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
