# Generated by Django 5.1.7 on 2026-05-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_coursepayment_mpesa_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
