# Generated by Django 5.1.7 on 2026-05-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_coursepayment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepayment',
            name='account_reference',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='payment_method',
            field=models.CharField(choices=[('stk', 'STK Push'), ('paybill', 'Paybill')], default='stk', max_length=20),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='transaction_status_request_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
