# Generated by Django 5.1.7 on 2026-05-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_coursepayment_account_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='payment_method',
            field=models.CharField(choices=[('stk', 'STK Push'), ('till', 'Till')], default='stk', max_length=20),
        ),
    ]
