# Generated by Django 5.1.7 on 2026-06-01 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_coursepayment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_slug', models.SlugField(max_length=80)),
                ('title', models.CharField(help_text='Example: Week 1 - June 2026', max_length=160)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('whatsapp_group_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-starts_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='enrollment_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='main.coursecohort'),
        ),
    ]
