from django.urls import path
from . import views

urlpatterns = [
    path('admin/', views.custom_admin_dashboard, name='custom_admin_dashboard'),
    path('admin/login/', views.custom_admin_login, name='custom_admin_login'),
    path('admin/logout/', views.custom_admin_logout, name='custom_admin_logout'),
    path('admin/profile/', views.custom_admin_profile, name='custom_admin_profile'),
    path('admin/seo/', views.custom_admin_seo, name='custom_admin_seo'),
    path('admin/course-weeks/', views.custom_admin_cohorts, name='custom_admin_cohorts'),
    path('admin/course-weeks/add/', views.custom_admin_cohort_edit, name='custom_admin_cohort_add'),
    path('admin/course-weeks/<int:pk>/delete/', views.custom_admin_cohort_delete, name='custom_admin_cohort_delete'),
    path('admin/course-weeks/<int:pk>/', views.custom_admin_cohort_edit, name='custom_admin_cohort_edit'),
    path('admin/projects/', views.custom_admin_projects, name='custom_admin_projects'),
    path('admin/projects/add/', views.custom_admin_project_edit, name='custom_admin_project_add'),
    path('admin/projects/<int:pk>/move/<str:direction>/', views.custom_admin_project_move, name='custom_admin_project_move'),
    path('admin/projects/<int:pk>/delete/', views.custom_admin_project_delete, name='custom_admin_project_delete'),
    path('admin/projects/<int:pk>/', views.custom_admin_project_edit, name='custom_admin_project_edit'),
    path('admin/posts/', views.custom_admin_posts, name='custom_admin_posts'),
    path('admin/posts/add/', views.custom_admin_post_edit, name='custom_admin_post_add'),
    path('admin/posts/<int:pk>/move/<str:direction>/', views.custom_admin_post_move, name='custom_admin_post_move'),
    path('admin/posts/<int:pk>/delete/', views.custom_admin_post_delete, name='custom_admin_post_delete'),
    path('admin/posts/<int:pk>/', views.custom_admin_post_edit, name='custom_admin_post_edit'),
    path('admin/payments/', views.custom_admin_payments, name='custom_admin_payments'),
    path('admin/payments/export/', views.custom_admin_payments_export, name='custom_admin_payments_export'),
    path('admin/payments/bulk-delete/', views.custom_admin_payments_bulk_delete, name='custom_admin_payments_bulk_delete'),
    path('admin/payments/<int:pk>/delete/', views.custom_admin_payment_delete, name='custom_admin_payment_delete'),
    path('admin/payments/<int:pk>/<str:action>/', views.custom_admin_payment_action, name='custom_admin_payment_action'),
    path('admin/contacts/', views.custom_admin_contacts, name='custom_admin_contacts'),
    path('', views.portfolio_home, name='portfolio_home'),
    path('', views.portfolio_home, name='home'),
    path('courses/', views.courses_home, name='courses_home'),
    path('courses/<slug:course_slug>/checkout/', views.course_checkout, name='course_checkout'),
    path('courses/payment/<int:payment_id>/', views.course_payment, name='course_payment'),
    path('courses/payment/<int:payment_id>/status/', views.course_payment_status, name='course_payment_status'),
    path('payments/mpesa/callback/', views.mpesa_callback, name='mpesa_callback'),
    path('payments/mpesa/c2b/validation/', views.mpesa_c2b_validation, name='mpesa_c2b_validation'),
    path('payments/mpesa/c2b/confirmation/', views.mpesa_c2b_confirmation, name='mpesa_c2b_confirmation'),
    path('payments/mpesa/transaction-status/result/', views.mpesa_transaction_status_result, name='mpesa_transaction_status_result'),
    path('payments/mpesa/transaction-status/timeout/', views.mpesa_transaction_status_timeout, name='mpesa_transaction_status_timeout'),
    path('blog/', views.blog_list, name='blog_list'),
    path('blog/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('robots.txt', views.robots_txt, name='robots_txt'),
    path('sitemap.xml', views.sitemap_xml, name='sitemap_xml'),
]

